theme: jekyll-theme-cayman
title: Presentations & Posters
description: This site serves as a repository for my conference and workshop presentations and posters. There may be a discrepancy between my C.V. and the presentations available here, but it is due to me switching computers a few times since some of the early presentations and not being able to locate a few of them.  

